version: '3.7'

services:
  frontend:
    depends_on:
      - backend
    image: node:latest
    volumes:
      - '.:/code'
    working_dir: '/code/frontend'
    command: bash -c "npm install; npm run dev"
    network_mode: host
  backend:
    build: .
    environment:
      - "BUILD_COMMAND=go build -o /tmp/build ./cmd/main" 
    volumes:
     - .:/code
    working_dir: /code 
    depends_on:
     - mysql
    network_mode: host
  mysql:
    image: mysql:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=root"

    volumes:
      - mysqldata:/var/lib/mysql:rw

volumes:
  mysqldata:
